// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import Modal-formController from "./modal-form_controller"
application.register("modal-form", Modal-formController)

import TurboController from "./turbo_controller"
application.register("turbo", TurboController)


